name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build WebToEpubKindle.sln --configuration Release
    - name: UnitTest
      run: dotnet test ./Test/WebToEpubKindle.UnitTest/WebToEpubKindle.UnitTest.csproj --verbosity normal
    - name: IntegratedTest
      run: sudo dotnet test ./Test/WebToEpubKindle.IntegrationTest/WebToEpubKindle.IntegrationTest.csproj --verbosity normal
